id: P3442277E
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Lodrö Rinchen
  language: nl
  description: 'Texts by Khenchen Ngawang Lodrö Rinchen (mkhan chen ngag dbang blo
    gros rin chen, 1892–1952):'
  volume:
    d1b94972101b4733beb40226120e9091:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Long Life Prayers
created_at: '2022-03-01T00:21:03.088791'
last_modified_at: '2022-03-01T00:21:03.088795'
